@accounts = http://localhost:8007/api/accounts
@auth = http://localhost:8007/api/auth
@content-type = application/bg.autohouse.api-v1+json
### Login
# @name loggedUser
POST {{auth}}/login HTTP/1.1
Content-Type: {{content-type}}

{
    "username": "vas@mail.com",
    "password": "123"
}

@token = {{loggedUser.response.body.$.data.token}}
###

POST {{accounts}}/private-create HTTP/1.1
Content-Type: {{content-type}}
Authorization: {{token}}

{
    "firstName": "Rhiannon",
    "lastName": "Hilpert",
    "displayName": "Barton - Lockman LLC",
    "description": "Dolorem dolor reiciendis.",
    "contactDetailsPhoneNumber": "1-108-227-7318 x0771",
    "contactDetailsWebLink": "https://landen.info",
    "accountType": "PRIVATE"
}


###

POST {{accounts}}/dealer-request HTTP/1.1
Content-Type: application/bg.autohouse.api-v1+json
Authorization: {{token}}

{
    "firstName": "Willa",
    "lastName": "Hodkiewicz",
    "displayName": "Schuppe Group and Sons",
    "description": "Nostrum saepe ut perferendis aperiam similique ipsum et.",
    "contactDetailsPhoneNumber": "970.105.0507",
    "contactDetailsWebLink": "http://wilbert.biz",
    "addressLocationId": 2521,
    "addressStreet": "5505 N. Summit Street",
    "accountType": "DEALER"
}
