@accounts = http://localhost:8007/api/accounts
@auth = http://localhost:8007/api/auth
@content-type = application/bg.autohouse.api-v1+json
@token = Bearer eyJraWQiOiJlYjczOGUwOS05YTkwLTQ5M2UtOWM3ZS04OWMxYTVlY2VkMmEiLCJhbGciOiJIUzUxMiJ9.eyJST0xFIjoiQURNSU4sVVNFUixNT0RFUkFUT1IsUk9PVCIsIlVTRVJfVVNFUk5BTUUiOiJ2YXNAbWFpbC5jb20iLCJKV1RfVUlEIjoiYzhmY2VlMTEtNzYwMC00ZDEwLWJkYTktN2QzYTRlZmI4OGZhIiwiSldUX1RZUEUiOiJBUElfQ0xJRU5UIiwiVVNFUl9VSUQgIjoiOTE1NWI2ZDItODFmZS00Mzc1LWIyNmItMjA3OGU0NmQ3M2JmIiwiZXhwIjoxNTg5MDIzMTA5LCJpYXQiOjE1ODgxNTkxMDl9.RCtehOVR3WWffekkqUJ1FILE00FkITt3676-O0L2Ivfv61XyzrUR4rZsQgpoCGIxU1vOhuAXPKXY2AeEb_G8LA

POST {{auth}}/login HTTP/1.1
Content-Type: {{content-type}}

{
    "username": "vas@mail.com",
    "password": "123"
}

###

POST {{accounts}}/private-create HTTP/1.1
Content-Type: {{content-type}}
Authorization: {{token}}

{
    "firstName": "Rhiannon",
    "lastName": "Hilpert",
    "displayName": "Barton - Lockman LLC",
    "description": "Dolorem dolor reiciendis.",
    "contactDetailsPhoneNumber": "1-108-227-7318 x0771",
    "contactDetailsWebLink": "https://landen.info",
    "accountType": "PRIVATE"
}


###

POST {{accounts}}/dealer-request HTTP/1.1
Content-Type: application/bg.autohouse.api-v1+json
Authorization: {{token}}

{
    "firstName": "Willa",
    "lastName": "Hodkiewicz",
    "displayName": "Schuppe Group and Sons",
    "description": "Nostrum saepe ut perferendis aperiam similique ipsum et.",
    "contactDetailsPhoneNumber": "970.105.0507",
    "contactDetailsWebLink": "http://wilbert.biz",
    "addressLocationId": 2521,
    "addressStreet": "5505 N. Summit Street",
    "accountType": "DEALER"
}