@images = http://localhost:8007/api/images
@auth = http://localhost:8007/api/auth
@content-type = application/bg.autohouse.api-v1+json

### Login
# @name loggedUser
POST {{auth}}/login HTTP/1.1
Content-Type: {{content-type}}

{
    "username": "vas@mail.com",
    "password": "123"
}

###

GET {{images}}/offer-images/2020/05/02/c7117172-f278-4f3c-8055-fc568a1d332c/2008_porsche_911_pic_1588392924865.jpg?thumbnail=true###


###
GET {{images}}/offer-images/2020/05/02/c7117172-f278-4f3c-8055-fc568a1d332c/2008_porsche_911_pic_1588392924865.jpg
