@images = http://localhost:8007/api/images
@auth = http://localhost:8007/api/auth
@content-type = application/bg.autohouse.api-v1+json

### Login
# @name loggedUser
POST {{auth}}/login HTTP/1.1
Content-Type: {{content-type}}

{
    "username": "vas@mail.com",
    "password": "123"
}

###

GET {{images}}/offer-images/2020/05/02/ec9a9fb8-4363-4314-bf85-0210282af6c7/2018_cadillac_xts_pic_1588401239124.jpg


###
GET {{images}}/offer-images/2020/05/02/ec9a9fb8-4363-4314-bf85-0210282af6c7/2018_cadillac_xts_pic_1588401239124.jpg?thumbnail=true


###


GET http://localhost:8007/site/images/body-styles/sedan.jpg
###
