@saerch_url = http://localhost:8007/api/vehicles/offers/search
@content-type = application/bg.autohouse.api-v1+json
@base = http://localhost:8007/api
@auth = http://localhost:8007/api/auth


###

POST {{saerch_url}}?page=0 HTTP/1.1
Content-Type: {{content-type}}

{
  "makerName": ""
}


### Login
# @name loggedUser
POST {{auth}}/login HTTP/1.1
Content-Type: {{content-type}}

{
    "username": "vas@mail.com",
    "password": "123"
}

@token = {{loggedUser.response.body.$.data.token}}

###
POST {{saerch_url}}/favorites?page=0 HTTP/1.1
Content-Type: {{content-type}}
Authorization: Bearer {{token}}

[
  "31a4a577-d9cf-4ca4-9c8e-383f8812e449",
  "84eca97e-c3c1-4de8-92da-f59054c7a66a"
]

