@host = http://localhost:8007/api/vehicles
@users = http://localhost:8007/api/users
@auth = http://localhost:8007/api/auth

GET {{host}}/state  HTTP/1.1
Accept: application/bg.autohouse.api-v1+json

###
### GET All makers available
GET {{host}}/makers  HTTP/1.1
Accept: application/bg.autohouse.api-v1+json

###

POST  {{host}}/makers HTTP/1.1
Accept:  application/bg.autohouse.api-v1+json
Content-Type: application/bg.autohouse.api-v1+json

{
  "name": "New Maker axcxcsdasd"
}

###

GET  {{host}}/makers/1 HTTP/1.1
Authorization: Bearer eyJraWQiOiI5NmQ4YTU1NC04NjM1LTQwMTktYTUzZC1mNGQ4NWY5MzE2NTMiLCJhbGciOiJIUzUxMiJ9.eyJVU0VSX1VTRVJOQU1FIjoidmFzQG1haWwuY29tIiwiZXhwIjoxNTg3NTQ0MzMxLCJUWVBFIjoiVkVSSUZJQ0FUSU9OIiwiaWF0IjoxNTg2NjgwMzMxfQ.NUn040UIApgstCVBUFlg1n5FiBWpV0-uzG8vHfZXwFehKln7U0l6ck_BXY-cDc37_8deMImCOlZS1XTF-cFRyw


###

POST {{host}}/makers/1 HTTP/1.1
Accept: application/bg.autohouse.api-v1+json
Content-Type: application/bg.autohouse.api-v1+json
Authorization: Bearer eyJraWQiOiI3ZjAxZjE2Mi0yNTVkLTQwNjQtYTI5NC04NGM2MzIyM2MxZmQiLCJhbGciOiJIUzUxMiJ9.eyJVU0VSX1VTRVJOQU1FIjoic2ltcGxlX3VzZXJAbWFpbC5jb20iLCJVU0VSX1VJRCI6ImZjYzZiNGFlLWVlNTAtNDA0My1hNjE2LWU1ODE0ZTk2Yjg4OCIsImV4cCI6MTU4NzUzMzMxOSwiVFlQRSI6IlZFUklGSUNBVElPTiIsImlhdCI6MTU4NjY2OTMxOSwiU1lTVEVNX1JPTEVfS0VZIjoiVVNFUiJ9.PaIWPMkl3l2rHfB_qIAlJlNLsO3jAjCIR56FaVgJKtK9oEI9iD3fWvSrGRPKeEA4PXhYOarZqQHy0GjfHnbpbA

{
  "name": "Naadsfdfdasddxzxa",
  "makerId": 1
}
###

GET  {{host}}/offers/nklnl HTTP/1.1
Accept: application/bg.autohouse.api-v1+json
Content-Type: application/bg.autohouse.api-v1+json

###
POST {{host}}/offers/search?page=1&size=5 HTTP/1.1
Accept: application/bg.autohouse.api-v1+json
Content-Type: application/bg.autohouse.api-v1+json

{
  "fuelType": "ELECTRIC"
}


###
POST {{auth}}/register HTTP/1.1
Accept: application/bg.autohouse.api-v1+json
Content-Type: application/bg.autohouse.api-v1+json

{
  "username": "email@emai.com",
  "password": "123456",
  "confirmPassword": "123456"
}

###
GET {{auth}}/register/verify?token=eyJraWQiOiI4YzE0Y2JlZS0zZDkzLTQwMjUtOWIzZC1jYzI5YzEyZDE2ZTUiLCJhbGciOiJIUzUxMiJ9.eyJVU0VSX1VTRVJOQU1FIjoiZW1haWxAZW1haS5jb20iLCJleHAiOjE1ODY1MDI2NTQsIlRZUEUiOiJSRUdJU1RSQVRJT04iLCJpYXQiOjE1ODY1MDIyMzR9.dCyeWlDQ389qqoiHUI1zDbV70eYVTh-jcRiO4ThDlflANfb7xs3R00lhkw_r89lYruYAVChrNHtO5o7u4w63ew
Accept: application/bg.autohouse.api-v1+json


###

POST {{auth}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "simple_user@mail.com",
    "password": "123"
}


###

POST {{users}}/account/private HTTP/1.1
Accept: application/bg.autohouse.api-v1+json
Content-Type: application/bg.autohouse.api-v1+json
Authorization: Bearer eyJraWQiOiI5NmQ4YTU1NC04NjM1LTQwMTktYTUzZC1mNGQ4NWY5MzE2NTMiLCJhbGciOiJIUzUxMiJ9.eyJVU0VSX1VTRVJOQU1FIjoidmFzQG1haWwuY29tIiwiZXhwIjoxNTg3NTQ0MzMxLCJUWVBFIjoiVkVSSUZJQ0FUSU9OIiwiaWF0IjoxNTg2NjgwMzMxfQ.NUn040UIApgstCVBUFlg1n5FiBWpV0-uzG8vHfZXwFehKln7U0l6ck_BXY-cDc37_8deMImCOlZS1XTF-cFRyw


{
    "firstName": "firstName",
    "lastName": "lastName"
}


###

GET {{auth}}/logout HTTP/1.1
Authorization: Bearer eyJraWQiOiI5NmQ4YTU1NC04NjM1LTQwMTktYTUzZC1mNGQ4NWY5MzE2NTMiLCJhbGciOiJIUzUxMiJ9.eyJVU0VSX1VTRVJOQU1FIjoidmFzQG1haWwuY29tIiwiZXhwIjoxNTg3NTQ0MzMxLCJUWVBFIjoiVkVSSUZJQ0FUSU9OIiwiaWF0IjoxNTg2NjgwMzMxfQ.NUn040UIApgstCVBUFlg1n5FiBWpV0-uzG8vHfZXwFehKln7U0l6ck_BXY-cDc37_8deMImCOlZS1XTF-cFRyw

###

POST {{auth}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "vas@mail.com",
    "password": "123"
}
