@host = http://localhost:8007/api/vehicles
@users = http://localhost:8007/api/users

GET {{host}}/state  HTTP/1.1
Accept: application/bg.autohouse.api-v1+json

###
### GET All makers available
GET {{host}}/makers/1  HTTP/1.1
Accept: application/bg.autohouse.api-v1+json

###

POST  {{host}}/makers HTTP/1.1
Accept:  application/bg.autohouse.api-v1+json
Content-Type: application/bg.autohouse.api-v1+json

{
  "name": "New Maker axcxcsdasd"
}

###

GET  {{host}}/makers/1 HTTP/1.1

###

POST {{host}}/makers/1 HTTP/1.1
Accept: application/bg.autohouse.api-v1+json
Content-Type: application/bg.autohouse.api-v1+json

{
  "name": "New asdxzxa",
  "makerId": 1
}
###

GET  {{host}}/offers/nklnl HTTP/1.1
Accept: application/bg.autohouse.api-v1+json
Content-Type: application/bg.autohouse.api-v1+json

###
POST {{host}}/offers/search?page=1&size=5 HTTP/1.1
Accept: application/bg.autohouse.api-v1+json
Content-Type: application/bg.autohouse.api-v1+json

{
  "fuelType": "ELECTRIC"
}


###
POST {{users}}/register HTTP/1.1
Accept: application/bg.autohouse.api-v1+json
Content-Type: application/bg.autohouse.api-v1+json

{
  "username": "username",
  "password": "123456",
  "confirmPassword": "123456",
  "phoneNumber": "123456",
  "email": "email@emai.com",
  "firstName": "firstName",
  "lastName": "lastName",
  "seller": "PRIVATE"
}
