@host = http://localhost:8007/api/vehicles
@users = http://localhost:8007/api/users

GET {{host}}/state  HTTP/1.1
Accept: application/bg.autohouse.api-v1+json

###
### GET All makers available
GET {{host}}/makers/1  HTTP/1.1
Accept: application/bg.autohouse.api-v1+json

###

POST  {{host}}/makers HTTP/1.1
Accept:  application/bg.autohouse.api-v1+json
Content-Type: application/bg.autohouse.api-v1+json

{
  "name": "New Maker axcxcsdasd"
}

###

GET  {{host}}/makers/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6IlVTRVIsIEFETUlOIiwiaWQiOiJhNmY4N2QxYS0xMjM2LTRkMzMtODcyZS02NzNlYTUxYTI3ZTUiLCJleHAiOjE1ODU5MTAyMDYsImlhdCI6MTU4NTA0NjIwNiwiZW1haWwiOiJlbWFpbEBlbWFpLmNvbSIsInVzZXJuYW1lIjoidXNlcm5hbWUifQ.8QNn4LHJBj5WM43qZDWwFCUw87Qv5Se6PpfuqNmZ5PjesNqI-Ki_ZmRXJ1N3pAGo4u19bwDmB3KwJ7Xdg1xI3A


###

POST {{host}}/makers/1 HTTP/1.1
Accept: application/bg.autohouse.api-v1+json
Content-Type: application/bg.autohouse.api-v1+json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6IlVTRVIsIEFETUlOIiwiaWQiOiJhNmY4N2QxYS0xMjM2LTRkMzMtODcyZS02NzNlYTUxYTI3ZTUiLCJleHAiOjE1ODU5MTAyMDYsImlhdCI6MTU4NTA0NjIwNiwiZW1haWwiOiJlbWFpbEBlbWFpLmNvbSIsInVzZXJuYW1lIjoidXNlcm5hbWUifQ.8QNn4LHJBj5WM43qZDWwFCUw87Qv5Se6PpfuqNmZ5PjesNqI-Ki_ZmRXJ1N3pAGo4u19bwDmB3KwJ7Xdg1xI3A

{
  "name": "Naadsfdfdasddxzxa",
  "makerId": 1
}
###

GET  {{host}}/offers/nklnl HTTP/1.1
Accept: application/bg.autohouse.api-v1+json
Content-Type: application/bg.autohouse.api-v1+json

###
POST {{host}}/offers/search?page=1&size=5 HTTP/1.1
Accept: application/bg.autohouse.api-v1+json
Content-Type: application/bg.autohouse.api-v1+json

{
  "fuelType": "ELECTRIC"
}


###
POST {{users}}/register HTTP/1.1
Accept: application/bg.autohouse.api-v1+json
Content-Type: application/bg.autohouse.api-v1+json

{
  "username": "username",
  "password": "123456",
  "confirmPassword": "123456",
  "phoneNumber": "123456",
  "email": "email@emai.com",
  "firstName": "firstName",
  "lastName": "lastName",
  "seller": "PRIVATE"
}


###

POST {{users}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "username",
    "password": "123456"
}
