package bg.autohouse.web.enums;

public enum RestMessage {
  REQUEST_SUCCESS,

  MAKERS_GET_SUCCESSFUL,
  MAKER_GET_SUCCESSFUL,
  MAKER_MODEL_CREATED,
  MAKER_CREATED,

  INITIAL_STATE_GET_SUCCESSFUL,

  REGISTRATION_VERIFICATION_TOKEN_SENT,
  PASSWORD_RESET_VERIFICATION_TOKEN_SENT,
  PASSWORD_RESET_SUCCESSFUL,
  USER_REGISTRATION_VERIFIED,
  USER_ALREADY_EXISTS,
  INVALID_REGISTRATION_TOKEN,
  INVALID_TOKEN,
  INVALID_USERNAME,
  LOGOUT_SUCCESSFUL,
  LOGOUT_FAILED,
  LOGIN_SUCCESSFUL,
  LOGIN_FAILED,

  USER_ALREADY_HAS_ACCOUNT,
  PRIVATE_SELLER_ACCOUNT_CREATED,
  INVALID_CREDENTIALS,
  OTP_VALID,
  OTP_INVALID,
}
