services:
  wiremock:
    image: vasatanasov/ah-wiremock-base:${AH_WIREMOCK_BASE_IMAGE_TAG}
#    image: vasatanasov/ah-wiremock-dev:${AH_WIREMOCK_DEV_IMAGE_TAG}
    container_name: wiremock
    command:
      - --proxy-all=${WIREMOCK_PROXY_ALL_HOST}
      - --record-mappings=${WIREMOCK_RECORD_MAPPINGS}
      - --verbose=${WIREMOCK_VERBOSE}
    environment:
      - UID=${UID}
      - WIREMOCK_HOME=${WIREMOCK_HOME}
      - WIREMOCK_ENABLED=${WIREMOCK_ENABLED}
    volumes:
      - /home/vas/projects/wiremock-mappings/original/__files:${WIREMOCK_HOME}/__files
      - /home/vas/projects/wiremock-mappings/original/mappings:${WIREMOCK_HOME}/mappings
    ports:
      - "${WIREMOCK_PORT}:8080"
    networks:
      - network

  spider:
    depends_on:
      - wiremock
    image: vasatanasov/ah-spider:${AH_SPIDER_IMAGE_TAG}
    container_name: spider
    environment:
      - STUBBING_ENABLED=${STUBBING_ENABLED}
      - FILE_STORAGE_FOLDER=${FILE_STORAGE_FOLDER}
    ports:
      - "8080:8080"
    networks:
      - network


networks:
  network: