services:
  mysql:
    image: vasatanasov/mysql-dev:${MYSQL_IMAGE_TAG}
    environment:
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - network

  server:
    image: vasatanasov/autohouse-server:${AUTOHOUSE_SERVER_IMAGE_TAG}
    depends_on:
      - mysql
    environment:
      # RDBMS
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_CONNECTION_URL=${DB_CONNECTION_URL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DDL_STRATEGY=none
      - TIME_ZONE=${TIME_ZONE}
    ports:
      - "8080:8080"
    networks:
      - network

volumes:
  mysql:

networks:
  network:
