server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
spring:
  liquibase:
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: bg.autohouse.backend.config.MySQL8UnicodeDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    generate-ddl: false
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_CONNECTION_URL}
  sql:
    init:
      platform: mysql